const distrt = [
    { name: 'Abim', region: 'Northern' },
    { name: 'Adjumani', region: 'Northern' },
    { name: 'Agago', region: 'Northern' },
    { name: 'Alebtong', region: 'Northern' },
    { name: 'Amolatar', region: 'Northern' },
    { name: 'Amudat', region: 'Northern' },
    { name: 'Amuria', region: 'Eastern' },
    { name: 'Amuru', region: 'Northern' },
    { name: 'Apac', region: 'Northern' },
    { name: 'Arua', region: 'Northern' },
    { name: 'Budaka', region: 'Eastern' },
    { name: 'Bududa', region: 'Eastern' },
    { name: 'Bugiri', region: 'Eastern' },
    { name: 'Bugweri', region: 'Eastern' },
    { name: 'Buhweju', region: 'Western' },
    { name: 'Buikwe', region: 'Central' },
    { name: 'Bukedea', region: 'Eastern' },
    { name: 'Bukomansimbi', region: 'Central' },
    { name: 'Bukwo', region: 'Eastern' },
    { name: 'Bulambuli', region: 'Eastern' },
    { name: 'Buliisa', region: 'Western' },
    { name: 'Bundibugyo', region: 'Western' },
    { name: 'Bunyangabu', region: 'Western' },
    { name: 'Bushenyi', region: 'Western' },
    { name: 'Busia', region: 'Eastern' },
    { name: 'Butaleja', region: 'Eastern' },
    { name: 'Butambala', region: 'Central' },
    { name: 'Butebo', region: 'Eastern' },
    { name: 'Buvuma', region: 'Central' },
    { name: 'Buyende', region: 'Eastern' },
    { name: 'Dokolo', region: 'Northern' },
    { name: 'Gomba', region: 'Central' },
    { name: 'Gulu', region: 'Northern' },
    { name: 'Hoima', region: 'Western' },
    { name: 'Ibanda', region: 'Western' },
    { name: 'Iganga', region: 'Eastern' },
    { name: 'Isingiro', region: 'Western' },
    { name: 'Jinja', region: 'Eastern' },
    { name: 'Kaabong', region: 'Northern' },
    { name: 'Kabale', region: 'Western' },
    { name: 'Kabarole', region: 'Western' },
    { name: 'Kaberamaido', region: 'Eastern' },
    { name: 'Kagadi', region: 'Western' },
    { name: 'Kakumiro', region: 'Western' },
    { name: 'Kalangala', region: 'Central' },
    { name: 'Kaliro', region: 'Eastern' },
    { name: 'Kalungu', region: 'Central' },
    { name: 'Kampala', region: 'Central' },
    { name: 'Kamuli', region: 'Eastern' },
    { name: 'Kamwenge', region: 'Western' },
    { name: 'Kanungu', region: 'Western' },
    { name: 'Kapchorwa', region: 'Eastern' },
    { name: 'Kapelebyong', region: 'Eastern' },
    { name: 'Karenga', region: 'Northern' },
    { name: 'Kasanda', region: 'Central' },
    { name: 'Kasese', region: 'Western' },
    { name: 'Katakwi', region: 'Eastern' },
    { name: 'Kayunga', region: 'Central' },
    { name: 'Kazo', region: 'Western' },
    { name: 'Kibaale', region: 'Western' },
    { name: 'Kiboga', region: 'Central' },
    { name: 'Kibuku', region: 'Eastern' },
    { name: 'Kikuube', region: 'Western' },
    { name: 'Kiruhura', region: 'Western' },
    { name: 'Kiryandongo', region: 'Western' },
    { name: 'Kisoro', region: 'Western' },
    { name: 'Kitagwenda', region: 'Western' },
    { name: 'Kitgum', region: 'Northern' },
    { name: 'Koboko', region: 'Northern' },
    { name: 'Kole', region: 'Northern' },
    { name: 'Kotido', region: 'Northern' },
    { name: 'Kumi', region: 'Eastern' },
    { name: 'Kwania', region: 'Northern' },
    { name: 'Kween', region: 'Eastern' },
    { name: 'Kyankwanzi', region: 'Central' },
    { name: 'Kyegegwa', region: 'Western' },
    { name: 'Kyenjojo', region: 'Western' },
    { name: 'Kyotera', region: 'Central' },
    { name: 'Lamwo', region: 'Northern' },
    { name: 'Lira', region: 'Northern' },
    { name: 'Luuka', region: 'Eastern' },
    { name: 'Luwero', region: 'Central' },
    { name: 'Lwengo', region: 'Central' },
    { name: 'Lyantonde', region: 'Central' },
    { name: 'Manafwa', region: 'Eastern' },
    { name: 'Maracha', region: 'Northern' },
    { name: 'Masaka', region: 'Central' },
    { name: 'Masindi', region: 'Western' },
    { name: 'Mayuge', region: 'Eastern' },
    { name: 'Mbale', region: 'Eastern' },
    { name: 'Mbarara', region: 'Western' },
    { name: 'Mitooma', region: 'Western' },
    { name: 'Mityana', region: 'Central' },
    { name: 'Moroto', region: 'Northern' },
    { name: 'Moyo', region: 'Northern' },
    { name: 'Mpigi', region: 'Central' },
    { name: 'Mubende', region: 'Central' },
    { name: 'Mukono', region: 'Central' },
    { name: 'Nabilatuk', region: 'Northern' },
    { name: 'Nakapiripirit', region: 'Northern' },
    { name: 'Nakaseke', region: 'Central' },
    { name: 'Nakasongola', region: 'Central' },
    { name: 'Namayingo', region: 'Eastern' },
    { name: 'Namisindwa', region: 'Eastern' },
    { name: 'Namutumba', region: 'Eastern' },
    { name: 'Napak', region: 'Northern' },
    { name: 'Nebbi', region: 'Northern' },
    { name: 'Ngora', region: 'Eastern' },
    { name: 'Ntoroko', region: 'Western' },
    { name: 'Ntungamo', region: 'Western' },
    { name: 'Nwoya', region: 'Northern' },
    { name: 'Obongi', region: 'Northern' },
    { name: 'Omoro', region: 'Northern' },
    { name: 'Otuke', region: 'Northern' },
    { name: 'Oyam', region: 'Northern' },
    { name: 'Pader', region: 'Northern' },
    { name: 'Pakwach', region: 'Northern' },
    { name: 'Pallisa', region: 'Eastern' },
    { name: 'Rakai', region: 'Central' },
    { name: 'Rubanda', region: 'Western' },
    { name: 'Rubirizi', region: 'Western' },
    { name: 'Rukiga', region: 'Western' },
    { name: 'Rukungiri', region: 'Western' },
    { name: 'Sembabule', region: 'Central' },
    { name: 'Serere', region: 'Eastern' },
    { name: 'Sheema', region: 'Western' },
    { name: 'Sironko', region: 'Eastern' },
    { name: 'Soroti', region: 'Eastern' },
    { name: 'Terego', region: 'Northern' },
    { name: 'Tororo', region: 'Eastern' },
    { name: 'Wakiso', region: 'Central' },
    { name: 'Yumbe', region: 'Northern' },
    { name: 'Zombo', region: 'Northern' }
];

const dist = document.querySelector('.district')

let select = document.createElement('select')
select.classList.add('form-control')
distrt.forEach(district =>{
    let option = document.createElement('option')
    option.value = district.name
    option.innerText = district.name

    select.appendChild(option)
    dist.appendChild(select)
})